new navbar
Mogobots/MogoZoo pull request #7
Opened 2022-07-14 04:15 UTC by XianBarbera

2022-07-14 04:16 UTC, ClaudioIrianni approved these changes
nice navbar

2022-07-14 07:10 UTC, PawFV requested changes

2022-07-14 07:10 UTC, PawFV commented on src/App.vue
> +      animal="Perro de mierda"
The name of the props begins to make little sense to me,
we have a `Card`, now if I want to use it for something other than animals, I have to pass `animal prop` which doesn't make sense.

Let's always think how we can name and build components in a way that can be reusable, not only for once specific thing.

I think we can rename this `prop` to `cardTitle` for now.

2022-07-14 07:49 UTC, PawFV requested changes

2022-07-14 07:52 UTC, PawFV commented on src/App.vue
> +      animal="Chiwawa, Angry Dog"
The name  `animal` for this `prop` make little sense.
We have a `Card`, now if I want to use it for something other than animals suppose, a list of T-shirts in the shopping section of the website, I have to pass `animal prop` which doesn't make sense.

Let's always think how we can name and build components in a way that can be reusable, not only for once specific thing.

I think we can rename this `prop` to `cardTitle` for now.

2022-07-16 23:11 UTC, XianBarbera commented
how do you like the changes?

2022-07-26 11:54 UTC, PawFV commented
> how do you like the changes?

@XianBarbera there are conflicts that block the merge to master, you need to solve them locally and push the changes.

2022-08-02 02:30 UTC, PawFV approved these changes

2022-08-02 02:31 UTC, merged